# --- build stage ---
FROM node:20-alpine AS build
WORKDIR /app
ENV CI=true
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build   # Vite соберёт в /app/dist

# --- serve via nginx ---
FROM nginx:1.27-alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/dist /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]
