<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputPath>../../../modules/</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../ModuleContract/ModuleContract.csproj" />
  </ItemGroup>

</Project>
